In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
import seaborn as sns

In [2]:
data=pd.read_csv("iris.csv")

In [3]:
data

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
x=data[['sepal_length','sepal_width','petal_length','petal_width']]

In [5]:
y=data['species']

In [6]:
x

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [7]:
y

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.3,shuffle=True)

In [12]:
classifiers=[]

In [13]:
from sklearn.svm import SVC
model1 = SVC()
classifiers.append(model1)


from sklearn import tree
model2 = tree.DecisionTreeClassifier()
classifiers.append(model2)


from sklearn.ensemble import RandomForestClassifier
model3 = RandomForestClassifier()
classifiers.append(model3)


from sklearn.linear_model import LogisticRegression
model4 = LogisticRegression()
classifiers.append(model4)


from sklearn.naive_bayes import GaussianNB
model5 = GaussianNB()
classifiers.append(model5)


from sklearn.metrics import accuracy_score, confusion_matrix

for clf in classifiers:
    clf.fit(X_train, y_train)
    y_pred=clf.predict(X_test)
    acc=accuracy_score(y_test,y_pred)
    print("Accuracy of %s is %s "%(clf,acc))
    cm=confusion_matrix(y_test,y_pred)
    print("Confusion Matrix of %s is \n%s "%(clf,cm))

Accuracy of SVC() is 1.0
Confusion Matrix of SVC() is
[[16  0  0]
 [ 0 15  0]
 [ 0  0 14]]
Accuracy of DecisionTreeClassifier() is 0.9777777777777777
Confusion Matrix of DecisionTreeClassifier() is
[[16  0  0]
 [ 0 14  1]
 [ 0  0 14]]
Accuracy of RandomForestClassifier() is 1.0
Confusion Matrix of RandomForestClassifier() is
[[16  0  0]
 [ 0 15  0]
 [ 0  0 14]]
Accuracy of LogisticRegression() is 1.0
Confusion Matrix of LogisticRegression() is
[[16  0  0]
 [ 0 15  0]
 [ 0  0 14]]
Accuracy of GaussianNB() is 1.0
Confusion Matrix of GaussianNB() is
[[16  0  0]
 [ 0 15  0]
 [ 0  0 14]]

C:\Users\Lenovo\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(